from .ma import MA_CONFIG, MA_INDICATORS
from .oscillators import OSC_CONFIG, OSC_INDICATORS
from .squeeze import SQUEEZE_CONFIG, SQUEEZE_INDICATORS
from .trend import TREND_CONFIG, TREND_INDICATORS
from .volatility import VOL_CONFIG, VOL_INDICATORS
from .volume import VOLU_CONFIG, VOLU_INDICATORS

AVAILABLE_INDICATORS = (
    MA_INDICATORS
    + OSC_INDICATORS
    + VOL_INDICATORS
    + VOLU_INDICATORS
    + TREND_INDICATORS
    + SQUEEZE_INDICATORS
)

INDICATOR_CONFIG = {}
for d in [MA_CONFIG, OSC_CONFIG, VOL_CONFIG, VOLU_CONFIG, TREND_CONFIG, SQUEEZE_CONFIG]:
    INDICATOR_CONFIG.update(d)
