"""Lazy application-layer exports for the unified ``src.candles`` module."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORTS = {
    "MarketMetaAPI": ".api",
    "calculate_notional_value": ".api",
    "get_funding_rate": ".api",
    "get_instrument_info": ".api",
    "get_liquidity_info": ".api",
    "get_mark_price": ".api",
    "get_open_interest": ".api",
    "refresh_okx_meta": ".api",
    "refresh_okx_meta_extended": ".api",
    "validate_order": ".api",
    "MetadataCachePort": ".metadata",
    "MetadataRefreshRequest": ".metadata",
    "MetadataRefreshResult": ".metadata",
    "MetadataSourcePort": ".metadata",
    "OrderValidationRequest": ".metadata",
    "OrderValidationResult": ".metadata",
    "ValidationQueryPort": ".metadata",
    "get_market_instrument_info": ".metadata",
    "refresh_market_metadata": ".metadata",
    "run_metadata_refresh_job": ".metadata",
    "validate_instrument_order": ".metadata",
    "dispatch_quality_alerts": ".quality_alerts",
    "run_quality_pipeline": ".quality_pipeline",
    "CandleStorePort": ".sync",
    "ExecutionMode": ".sync",
    "InstrumentCatalogPort": ".sync",
    "MarketDataPort": ".sync",
    "RefreshInstrumentCatalogUseCase": ".sync",
    "RetryPolicy": ".sync",
    "RunCandleSyncUseCase": ".sync",
    "SyncJobRequest": ".sync",
    "SyncJobResult": ".sync",
    "SyncPolicyConfig": ".sync",
    "SyncRun": ".sync",
    "SyncRunStatus": ".sync",
    "SyncStatePort": ".sync",
    "TelemetryPort": ".sync",
    "refresh_instrument_catalog": ".sync",
    "run_candle_sync": ".sync",
    "MODE_CONFIGS": ".sync_use_cases",
    "build_sync_config": ".sync_use_cases",
    "check_data_freshness": ".sync_use_cases",
    "format_stats_for_xcom": ".sync_use_cases",
    "resolve_sync_mode": ".sync_use_cases",
    "run_smoke_validation": ".sync_use_cases",
    "should_refresh_instruments": ".sync_use_cases",
}

__all__ = [
    "MODE_CONFIGS",
    "CandleStorePort",
    "ExecutionMode",
    "InstrumentCatalogPort",
    "MarketDataPort",
    "MarketMetaAPI",
    "MetadataCachePort",
    "MetadataRefreshRequest",
    "MetadataRefreshResult",
    "MetadataSourcePort",
    "OrderValidationRequest",
    "OrderValidationResult",
    "RefreshInstrumentCatalogUseCase",
    "RetryPolicy",
    "RunCandleSyncUseCase",
    "SyncJobRequest",
    "SyncJobResult",
    "SyncPolicyConfig",
    "SyncRun",
    "SyncRunStatus",
    "SyncStatePort",
    "TelemetryPort",
    "ValidationQueryPort",
    "build_sync_config",
    "calculate_notional_value",
    "check_data_freshness",
    "dispatch_quality_alerts",
    "format_stats_for_xcom",
    "get_funding_rate",
    "get_instrument_info",
    "get_liquidity_info",
    "get_mark_price",
    "get_market_instrument_info",
    "get_open_interest",
    "refresh_instrument_catalog",
    "refresh_market_metadata",
    "refresh_okx_meta",
    "refresh_okx_meta_extended",
    "resolve_sync_mode",
    "run_candle_sync",
    "run_metadata_refresh_job",
    "run_quality_pipeline",
    "run_smoke_validation",
    "should_refresh_instruments",
    "validate_instrument_order",
    "validate_order",
]


def __getattr__(name: str) -> Any:
    if name not in _EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(_EXPORTS[name], __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
