"""
Trend indicator specifications.

This module contains all trend-related feature specifications.
"""

from ..domain.models import FeatureSpec

# Trend indicators
TREND_FEATURES = {
    "adx_14": FeatureSpec(
        name="adx_14",
        type="trend",
        params={"period": 14},
        requires=["high", "low", "close"],
        description="Average Directional Index (14 periods)",
    ),
    "adx_pos_di": FeatureSpec(
        name="adx_pos_di",
        type="trend",
        params={"period": 14},
        requires=["high", "low", "close"],
        description="Positive Directional Indicator (+DI, 14 periods)",
    ),
    "adx_neg_di": FeatureSpec(
        name="adx_neg_di",
        type="trend",
        params={"period": 14},
        requires=["high", "low", "close"],
        description="Negative Directional Indicator (-DI, 14 periods)",
    ),
    "aroon_up": FeatureSpec(
        name="aroon_up",
        type="trend",
        params={"length": 14},
        requires=["high", "low"],
        description="Aroon Up (14 periods)",
    ),
    "aroon_down": FeatureSpec(
        name="aroon_down",
        type="trend",
        params={"length": 14},
        requires=["high", "low"],
        description="Aroon Down (14 periods)",
    ),
    "aroon_osc": FeatureSpec(
        name="aroon_osc",
        type="trend",
        params={"length": 14},
        requires=["high", "low"],
        description="Aroon Oscillator (Up-Down, 14 periods)",
    ),
    "cci_20": FeatureSpec(
        name="cci_20",
        type="trend",
        params={"period": 20},
        requires=["high", "low", "close"],
        description="Commodity Channel Index (20 periods)",
    ),
    "dpo_20": FeatureSpec(
        name="dpo_20",
        type="trend",
        params={"period": 20},
        requires=["close"],
        description="Detrended Price Oscillator (20 periods)",
    ),
    "ichimoku_tenkan": FeatureSpec(
        name="ichimoku_tenkan",
        type="trend",
        params={"tenkan": 9},
        requires=["high", "low"],
        description="Ichimoku Tenkan-sen (Conversion Line, 9)",
    ),
    "ichimoku_kijun": FeatureSpec(
        name="ichimoku_kijun",
        type="trend",
        params={"kijun": 26},
        requires=["high", "low"],
        description="Ichimoku Kijun-sen (Base Line, 26)",
    ),
    "ichimoku_senkou_a": FeatureSpec(
        name="ichimoku_senkou_a",
        type="trend",
        params={"tenkan": 9, "kijun": 26, "senkou": 26},
        requires=["high", "low"],
        description="Ichimoku Senkou Span A (Leading Span A, 9, 26)",
    ),
    "ichimoku_senkou_b": FeatureSpec(
        name="ichimoku_senkou_b",
        type="trend",
        params={"senkou_b": 52, "senkou": 26},
        requires=["high", "low"],
        description="Ichimoku Senkou Span B (Leading Span B, 52, 26)",
    ),
    "ichimoku_chikou": FeatureSpec(
        name="ichimoku_chikou",
        type="trend",
        params={"chikou": 26},
        requires=["close"],
        description="Ichimoku Chikou Span (Lagging Span, 26)",
    ),
    "kst": FeatureSpec(
        name="kst",
        type="trend",
        params={
            "r1": 10,
            "r2": 15,
            "r3": 20,
            "r4": 30,
            "s1": 9,
            "s2": 9,
            "s3": 9,
            "s4": 9,
        },
        requires=["close"],
        description="Know Sure Thing indicator",
    ),
    "mom_10": FeatureSpec(
        name="mom_10",
        type="trend",
        params={"period": 10},
        requires=["close"],
        description="Momentum (10 periods)",
    ),
    "ppo": FeatureSpec(
        name="ppo",
        type="trend",
        params={"fast_period": 12, "slow_period": 26, "signal_period": 9},
        requires=["close"],
        description="Percentage Price Oscillator (12, 26, 9)",
    ),
    "roc_10": FeatureSpec(
        name="roc_10",
        type="trend",
        params={"period": 10},
        requires=["close"],
        description="Rate of Change (10 periods)",
    ),
    "stoch_k": FeatureSpec(
        name="stoch_k",
        type="trend",
        params={"k_period": 14, "d_period": 3},
        requires=["high", "low", "close"],
        description="Stochastic %K (14, 3)",
    ),
    "stoch_d": FeatureSpec(
        name="stoch_d",
        type="trend",
        params={"k_period": 14, "d_period": 3},
        requires=["high", "low", "close"],
        description="Stochastic %D (14, 3)",
    ),
    "trix": FeatureSpec(
        name="trix",
        type="trend",
        params={"period": 18},
        requires=["close"],
        description="TRIX (18 periods)",
    ),
    "tsf": FeatureSpec(
        name="tsf",
        type="trend",
        params={"period": 14},
        requires=["close"],
        description="Time Series Forecast (14 periods)",
    ),
    "ultosc": FeatureSpec(
        name="ultosc",
        type="trend",
        params={"period1": 7, "period2": 14, "period3": 28},
        requires=["high", "low", "close"],
        description="Ultimate Oscillator (7, 14, 28)",
    ),
    "willr": FeatureSpec(
        name="willr",
        type="trend",
        params={"period": 14},
        requires=["high", "low", "close"],
        description="Williams %R (14 periods)",
    ),
}

# Stage E: Additional trend indicators
TREND_STAGE_E = {
    "amat": FeatureSpec(
        name="amat",
        type="trend",
        params={"length": 14},
        requires=["close"],
        description="Aroon Mean Reversion",
    ),
    "chop": FeatureSpec(
        name="chop",
        type="trend",
        params={"length": 14},
        requires=["high", "low", "close"],
        description="Choppiness Index",
    ),
    "decay": FeatureSpec(
        name="decay",
        type="trend",
        params={"length": 5},
        requires=["close"],
        description="Decay",
    ),
    "decreasing": FeatureSpec(
        name="decreasing",
        type="trend",
        params={"length": 5},
        requires=["close"],
        description="Decreasing",
    ),
    "dpo": FeatureSpec(
        name="dpo",
        type="trend",
        params={"length": 20},
        requires=["close"],
        description="Detrended Price Oscillator",
    ),
    "increasing": FeatureSpec(
        name="increasing",
        type="trend",
        params={"length": 5},
        requires=["close"],
        description="Increasing",
    ),
    "long_run": FeatureSpec(
        name="long_run",
        type="trend",
        params={"length": 2},
        requires=["close"],
        description="Long Run",
    ),
    "psar": FeatureSpec(
        name="psar",
        type="trend",
        params={"af": 0.02, "max_af": 0.2},
        requires=["high", "low", "close"],
        description="Parabolic SAR",
    ),
    "psar_direction": FeatureSpec(
        name="psar_direction",
        type="trend",
        params={"af": 0.02, "max_af": 0.2},
        requires=["high", "low", "close"],
        description="Parabolic SAR Direction",
    ),
    "psar_long": FeatureSpec(
        name="psar_long",
        type="trend",
        params={"af": 0.02, "max_af": 0.2},
        requires=["high", "low", "close"],
        description="Parabolic SAR Long Line",
    ),
    "psar_short": FeatureSpec(
        name="psar_short",
        type="trend",
        params={"af": 0.02, "max_af": 0.2},
        requires=["high", "low", "close"],
        description="Parabolic SAR Short Line",
    ),
    "supertrend": FeatureSpec(
        name="supertrend",
        type="trend",
        params={"length": 10, "mult": 3.0},
        requires=["high", "low", "close"],
        description="Supertrend value",
    ),
    "supertrend_direction": FeatureSpec(
        name="supertrend_direction",
        type="trend",
        params={"length": 10, "mult": 3.0},
        requires=["high", "low", "close"],
        description="Supertrend direction",
    ),
    "supertrend_long": FeatureSpec(
        name="supertrend_long",
        type="trend",
        params={"length": 10, "mult": 3.0},
        requires=["high", "low", "close"],
        description="Supertrend long line",
    ),
    "supertrend_short": FeatureSpec(
        name="supertrend_short",
        type="trend",
        params={"length": 10, "mult": 3.0},
        requires=["high", "low", "close"],
        description="Supertrend short line",
    ),
    "qstick": FeatureSpec(
        name="qstick",
        type="trend",
        params={"length": 14},
        requires=["open", "close"],
        description="QStick",
    ),
    "short_run": FeatureSpec(
        name="short_run",
        type="trend",
        params={"length": 2},
        requires=["close"],
        description="Short Run",
    ),
    "ttm_trend": FeatureSpec(
        name="ttm_trend",
        type="trend",
        params={"length": 5},
        requires=["close"],
        description="TTM Trend",
    ),
    "vortex": FeatureSpec(
        name="vortex",
        type="trend",
        params={"length": 14},
        requires=["high", "low", "close"],
        description="Vortex Indicator",
    ),
}
