"""Feature-specific ORM models."""

from __future__ import annotations

from sqlalchemy import (
    BigInteger,
    Column,
    DateTime,
    Numeric,
    SmallInteger,
    String,
)
from sqlalchemy.orm import declarative_base

from ..storage_contract import IndicatorStorageContract

FeaturesBase = declarative_base()


class Indicator(FeaturesBase):
    __tablename__ = IndicatorStorageContract.table_name

    symbol = Column(String, primary_key=True)
    timeframe = Column(String, primary_key=True)
    timestamp = Column(BigInteger, primary_key=True)

    rsi_14 = Column(Numeric, nullable=True)
    ema_12 = Column(Numeric, nullable=True)
    ema_21 = Column(Numeric, nullable=True)
    ema_26 = Column(Numeric, nullable=True)
    ema_50 = Column(Numeric, nullable=True)
    ema_200 = Column(Numeric, nullable=True)
    sma_34 = Column(Numeric, nullable=True)
    sma_50 = Column(Numeric, nullable=True)
    sma_200 = Column(Numeric, nullable=True)
    macd = Column(Numeric, nullable=True)
    macd_signal = Column(Numeric, nullable=True)
    macd_histogram = Column(Numeric, nullable=True)
    bb_upper = Column(Numeric, nullable=True)
    bb_middle = Column(Numeric, nullable=True)
    bb_lower = Column(Numeric, nullable=True)
    stoch_k = Column(Numeric, nullable=True)
    stoch_d = Column(Numeric, nullable=True)
    atr_14 = Column(Numeric, nullable=True)
    volume_sma20 = Column(Numeric, nullable=True)
    ichimoku_tenkan = Column(Numeric, nullable=True)
    ichimoku_kijun = Column(Numeric, nullable=True)
    ichimoku_senkou_a = Column(Numeric, nullable=True)
    ichimoku_senkou_b = Column(Numeric, nullable=True)
    ichimoku_chikou = Column(Numeric, nullable=True)
    adx_14 = Column(Numeric, nullable=True)
    adx_pos_di = Column(Numeric, nullable=True)
    adx_neg_di = Column(Numeric, nullable=True)
    obv = Column(Numeric, nullable=True)
    cmf = Column(Numeric, nullable=True)
    vwap = Column(Numeric, nullable=True)
    vp_value_area_high = Column(Numeric, nullable=True)
    vp_value_area_low = Column(Numeric, nullable=True)
    vp_point_of_control = Column(Numeric, nullable=True)
    kc_upper = Column(Numeric, nullable=True)
    kc_middle = Column(Numeric, nullable=True)
    kc_lower = Column(Numeric, nullable=True)
    ttm_squeeze_on = Column(Numeric, nullable=True)
    ttm_squeeze_hist = Column(Numeric, nullable=True)
    ttm_squeeze_value = Column(Numeric, nullable=True)
    ema_8 = Column(Numeric, nullable=True)
    ema_13 = Column(Numeric, nullable=True)
    ema_34 = Column(Numeric, nullable=True)
    ema_55 = Column(Numeric, nullable=True)
    ema_89 = Column(Numeric, nullable=True)
    ema_144 = Column(Numeric, nullable=True)
    ema_233 = Column(Numeric, nullable=True)
    ha_open = Column(Numeric, nullable=True)
    ha_high = Column(Numeric, nullable=True)
    ha_low = Column(Numeric, nullable=True)
    ha_close = Column(Numeric, nullable=True)
    cdl_doji = Column(SmallInteger, nullable=True)
    cdl_inside = Column(SmallInteger, nullable=True)
    drawdown = Column(Numeric, nullable=True)
    log_return = Column(Numeric, nullable=True)
    percent_return = Column(Numeric, nullable=True)
    trend_return_20 = Column(Numeric, nullable=True)
    returns_20 = Column(Numeric, nullable=True)
    volatility_20 = Column(Numeric, nullable=True)
    sharpe_20 = Column(Numeric, nullable=True)
    max_drawdown_20 = Column(Numeric, nullable=True)
    hl2 = Column(Numeric, nullable=True)
    hlc3 = Column(Numeric, nullable=True)
    ohlc4 = Column(Numeric, nullable=True)
    midpoint = Column(Numeric, nullable=True)
    midprice = Column(Numeric, nullable=True)
    wcp = Column(Numeric, nullable=True)
    hwma_20 = Column(Numeric, nullable=True)
    rma_20 = Column(Numeric, nullable=True)
    ics_26 = Column(Numeric, nullable=True)
    t3_20 = Column(Numeric, nullable=True)
    ttm_trend = Column(Numeric, nullable=True)
    decay = Column(Numeric, nullable=True)
    long_run = Column(Numeric, nullable=True)
    decreasing = Column(Numeric, nullable=True)
    increasing = Column(Numeric, nullable=True)
    amat = Column(Numeric, nullable=True)
    short_run = Column(Numeric, nullable=True)
    pvi = Column(Numeric, nullable=True)
    ad = Column(Numeric, nullable=True)
    rsx_14 = Column(Numeric, nullable=True)
    trange = Column(Numeric, nullable=True)
    nvi = Column(Numeric, nullable=True)
    bop = Column(Numeric, nullable=True)
    rsx = Column(Numeric, nullable=True)
    calculated_at = Column(DateTime(timezone=True), nullable=True)
    data_status = Column(String(10), nullable=True, server_default="ok")
    failed_groups = Column(String, nullable=True)
    pwma_20 = Column(Numeric, nullable=True)
    slope_20 = Column(Numeric, nullable=True)
    vidya_20 = Column(Numeric, nullable=True)
    median_20 = Column(Numeric, nullable=True)
    aroon_up = Column(Numeric, nullable=True)
    wma_20 = Column(Numeric, nullable=True)
    inertia = Column(Numeric, nullable=True)
    mad_20 = Column(Numeric, nullable=True)
    vortex = Column(Numeric, nullable=True)
    er = Column(Numeric, nullable=True)
    dc_upper = Column(Numeric, nullable=True)
    rvgi = Column(Numeric, nullable=True)
    kurtosis_20 = Column(Numeric, nullable=True)
    zlma_20 = Column(Numeric, nullable=True)
    dema_20 = Column(Numeric, nullable=True)
    rvi = Column(Numeric, nullable=True)
    ao = Column(Numeric, nullable=True)
    pdist = Column(Numeric, nullable=True)
    trix = Column(Numeric, nullable=True)
    mfi = Column(Numeric, nullable=True)
    kama_20 = Column(Numeric, nullable=True)
    cg = Column(Numeric, nullable=True)
    linreg_20 = Column(Numeric, nullable=True)
    roc_10 = Column(Numeric, nullable=True)
    variance_20 = Column(Numeric, nullable=True)
    fwma_20 = Column(Numeric, nullable=True)
    natr_14 = Column(Numeric, nullable=True)
    sma_20 = Column(Numeric, nullable=True)
    cci_20 = Column(Numeric, nullable=True)
    hma_20 = Column(Numeric, nullable=True)
    cfo = Column(Numeric, nullable=True)
    parkinson_vol = Column(Numeric, nullable=True)
    adosc = Column(Numeric, nullable=True)
    dc_lower = Column(Numeric, nullable=True)
    fisher = Column(Numeric, nullable=True)
    alma_20 = Column(Numeric, nullable=True)
    apo = Column(Numeric, nullable=True)
    vwma = Column(Numeric, nullable=True)
    var_20 = Column(Numeric, nullable=True)
    brar = Column(Numeric, nullable=True)
    pvt = Column(Numeric, nullable=True)
    willr = Column(Numeric, nullable=True)
    massi = Column(Numeric, nullable=True)
    tsi = Column(Numeric, nullable=True)
    aroon_osc = Column(Numeric, nullable=True)
    trima_20 = Column(Numeric, nullable=True)
    bias = Column(Numeric, nullable=True)
    kurt_20 = Column(Numeric, nullable=True)
    ppo = Column(Numeric, nullable=True)
    zscore_20 = Column(Numeric, nullable=True)
    stdev_20 = Column(Numeric, nullable=True)
    smi = Column(Numeric, nullable=True)
    pvo = Column(Numeric, nullable=True)
    tema_20 = Column(Numeric, nullable=True)
    dc_middle = Column(Numeric, nullable=True)
    pgo = Column(Numeric, nullable=True)
    sinwma_20 = Column(Numeric, nullable=True)
    eri = Column(Numeric, nullable=True)
    swma_20 = Column(Numeric, nullable=True)
    skew_20 = Column(Numeric, nullable=True)
    aroon_down = Column(Numeric, nullable=True)
    psl = Column(Numeric, nullable=True)
    coppock = Column(Numeric, nullable=True)
    uo = Column(Numeric, nullable=True)
    ultosc = Column(Numeric, nullable=True)
    std_20 = Column(Numeric, nullable=True)
    ui = Column(Numeric, nullable=True)
    qstick = Column(Numeric, nullable=True)
    psar = Column(Numeric, nullable=True)
    psar_direction = Column(Numeric, nullable=True)
    psar_long = Column(Numeric, nullable=True)
    psar_short = Column(Numeric, nullable=True)
    supertrend = Column(Numeric, nullable=True)
    supertrend_direction = Column(Numeric, nullable=True)
    supertrend_long = Column(Numeric, nullable=True)
    supertrend_short = Column(Numeric, nullable=True)
    chop = Column(Numeric, nullable=True)
    dpo = Column(Numeric, nullable=True)
    stochrsi_k = Column(Numeric, nullable=True)
    stochrsi_d = Column(Numeric, nullable=True)
    kdj_k = Column(Numeric, nullable=True)
    kdj_d = Column(Numeric, nullable=True)


class CalculationMetadata(FeaturesBase):
    """Metadata for feature calculations to enable ML reproducibility."""

    __tablename__ = "calculation_metadata"

    snapshot_id = Column(String(50), primary_key=True)
    created_at = Column(DateTime(timezone=True), nullable=False)
    completed_at = Column(DateTime(timezone=True), nullable=True)
    algorithm_version = Column(String(20), nullable=False)
    module_version = Column(String(20), nullable=False, default="1.0.0")
    config = Column(String, nullable=False)
    symbols = Column(String, nullable=True)
    timeframes = Column(String, nullable=True)
    status = Column(String(20), nullable=False, default="in_progress")
    rows_calculated = Column(BigInteger, default=0)
    execution_duration_seconds = Column(Numeric(10, 2), nullable=True)
    error_message = Column(String, nullable=True)
