FROM apache/airflow:2.9.3

USER root

COPY . /opt/airflow/project/
RUN chown -R airflow:root /opt/airflow/project/

COPY ops/airflow/dags /opt/airflow/dags/
RUN chown -R airflow:root /opt/airflow/dags/

USER airflow
RUN pip install --no-cache-dir -r /opt/airflow/project/ops/airflow/requirements-airflow.txt
