"""Logging configuration for the features module.

DEPRECATED: This module is now a re-export from src.logging.
Please use `from src.logging import ...` directly.

All functionality has been moved to the unified logging module at src/logging/.
This module is kept for backward compatibility only.
"""

import warnings

# Emit deprecation warning on import (only once per session)
warnings.warn(
    "src.features.observability.logging is deprecated. "
    "Use src.logging instead for new code.",
    DeprecationWarning,
    stacklevel=2,
)

# Re-export everything from the new unified logging module
from src.logging import (
    LOG_DIR,
    AggregatedMetric,
    CategoryAdapter,
    CategoryFilter,
    CompactFormatter,
    ContextFilter,
    JsonFormatter,
    LogAggregator,
    LogCategory,
    OperationContext,
    RunSummary,
    SensitiveDataFilter,
    Verbosity,
    _build_console_handler,
    _build_file_handler,
    _build_formatter,
    create_run_summary,
    generate_run_id,
    get_category_logger,
    get_current_context,
    get_current_run_id,
    get_features_logger,
    get_log_backup_count,
    get_log_dir,
    get_log_directory,
    get_log_file_max_bytes,
    get_log_format,
    get_log_level,
    get_logger,
    get_verbosity,
    is_category_enabled,
    log_bad_record,
    log_batch_metrics,
    log_feature_quality,
    log_features_summary,
    log_function_call,
    log_operation,
    log_sample_record,
    log_schema_mismatch,
    performance_timer,
    set_enabled_categories,
    set_log_context,
    set_verbosity,
    setup_features_logging,
    setup_logging,
    should_log,
)

__all__ = [
    "LOG_DIR",
    "AggregatedMetric",
    "CategoryAdapter",
    "CategoryFilter",
    "CompactFormatter",
    "ContextFilter",
    "JsonFormatter",
    "LogAggregator",
    "LogCategory",
    "OperationContext",
    "RunSummary",
    "SensitiveDataFilter",
    "Verbosity",
    "_build_console_handler",
    "_build_file_handler",
    "_build_formatter",
    "create_run_summary",
    "generate_run_id",
    "get_category_logger",
    "get_current_context",
    "get_current_run_id",
    "get_features_logger",
    "get_log_backup_count",
    "get_log_dir",
    "get_log_directory",
    "get_log_file_max_bytes",
    "get_log_format",
    "get_log_level",
    "get_logger",
    "get_verbosity",
    "is_category_enabled",
    "log_bad_record",
    "log_batch_metrics",
    "log_feature_quality",
    "log_features_summary",
    "log_function_call",
    "log_operation",
    "log_sample_record",
    "log_schema_mismatch",
    "performance_timer",
    "set_enabled_categories",
    "set_log_context",
    "set_verbosity",
    "setup_features_logging",
    "setup_logging",
    "should_log",
]
